[package]
name = "ddrpc"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
common = { workspace = true }
clap = { version = "4.5.11", features = ["derive"] }
tokio = { version = "1.39.2", features = ["full"] }
